### ISSUE TITLE
Extracting passwords

### ISSUE THREAD

**Issue by miaoct** [HighwayWu/ST-DDL#1]
I have downloaded the ManualFake_2022.zip, but I can not extract it.

Can you provide the passwords for unzip?

Thank you!

**Comment by mittalgovind** [comment]
When are you expecting to release the dataset?

**Comment by HighwayWu** [comment]
Thanks for your interest and sorry for the delay. As the relevant licenses are being produced, this dataset (the password) is expected to be officially released within this month.

**Comment by mittalgovind** [comment]
Thanks for the reply. Just inquiring about any progress made towards the release?

**Comment by HighwayWu** [comment]
Thanks for your kind patience. The unzip code could be obtained by fill the Google Form (https://forms.gle/kbPhLw7ihfdnwerg8).
